### ISSUE TITLE
[The App] Authentication Logic

### ISSUE THREAD

**Issue by ChristophNetsch** [Aktion-Sodis/software-main#21]
Implement logic to authenticate with Amplify Auth from Flutter, see [example ](https://docs.amplify.aws/lib/auth/getting-started/q/platform/flutter/#initialize-amplify-auth). Required functionality:

- [ ] Login via phone number.
- [ ] Login via email.
- [ ] (optional) Login via WhatsApp, if possible.

**Comment by ChristophNetsch** [comment]
@CoachBenedetto Kannst du mich assignen? Glaube, ich habe hier noch nicht die Rechte, um das selber zu machen.

**Comment by CoachBenedetto** [comment]
Habe ein File authentication erstellt. Die Login-Methoden muss ich noch im Backend freischalten, sollte aber beim implementieren kein Problem sein👍
