### ISSUE TITLE
Backend Database Migration

### ISSUE THREAD

**Issue by ChristophNetsch** [Aktion-Sodis/software-main#28]
Migrate data from app version 1 database (MariaDB) to new database schema. Script is to be stored in new folder lib/scripts.

**Comment by ChristophNetsch** [comment]
@CoachBenedetto Stört es dich, wenn ich hierzu Python nehme oder bringt das dir den tech stack durcheinander? Damit wäre ich deutlich schneller.

**Comment by CoachBenedetto** [comment]
Ne, alles gut. Es gibt allerdings mittlerweile Admin-Queries bei uns im amplify backend (für NodeJS). Wirf da vielleicht mal nen Blick drauf, könnte hilfreich sein. Ansonsten sag Bescheid wo du Unterstützung brauchst. Hatte das hier leider nicht gesehen @ChristophNetsch

**Comment by ChristophNetsch** [comment]
@apolat2000 Habe die Migration so weit vorbereitet. Ich update meinen Code nochmal, sobald du die Datenbankstruktur modifiziert hast.
