### ISSUE TITLE
Backend - Connection of Survey and Survey Type is missing

### ISSUE THREAD

**Issue by CoachBenedetto** [Aktion-Sodis/software-main#44]
Add the survey tape field to survey and update it in admin app as well as mobile app including
- callableModels/Survey
- repositories/...

**Comment by apolat2000** [comment]
Who can take this on? Is anyone currently working on this? @CoachBenedetto

**Comment by CoachBenedetto** [comment]
Further change tag properties from String to Tag (own collection). Each tag contains of it's id and name
