### ISSUE TITLE
[The App] Page for accepting permissions

### ISSUE THREAD

**Issue by arthur-becker** [Aktion-Sodis/software-main#54]
**Is your feature request related to a problem? Please describe.**
The user has to actively accept permissions in order to use some features, like recording or taking pictures.

**Describe the solution you'd like**
A good solution for now is to ask the user for all permissions, when the app is running for the first time, and to explain, why the app needs these permissions. Currently, the app needs two permissions:

1. Camera
2. Audio recording

**Comment by CoachBenedetto** [comment]
@arthur-becker we further need permission for localization (to store the localizations of interventions, surveys, e.g.). Can you implement the request on app-start (if not given before). There exist default dialogs by flutter I think
