### ISSUE TITLE
[Admin-App] Error handling for the Authentication Flows

### ISSUE THREAD

**Issue by apolat2000** [Aktion-Sodis/software-main#60]
Currently, not all errors are handled correctly for the authentication flows. The flows are:

- [x] Login
- [x] Complete user information
- [x] Update password
- [x] Forgot password

Convey a bug hunting and test the edge cases to determine the unhandled errors/exceptions from the Amplify API. Then create the corresponding entries in `en-US.json`, `es-ES.json` and `tr-TR.json` and show them with the help of the feedback module of the store.

Tip: Error code entries for i18n were created under `general.errorCodes` until now.

**Comment by behlulbozal** [comment]
[60](https://github.com/Aktion-Sodis/software-main/pull/75)

**Comment by behlulbozal** [comment]
[PR](https://github.com/Aktion-Sodis/software-main/pull/75)
