### ISSUE TITLE
[Admin-App] i18n consistency

### ISSUE THREAD

**Issue by apolat2000** [Aktion-Sodis/software-main#61]
Currently, there is an inconsistency between `en-US.json` `es-ES.json` `tr-TR.json`. These can be described as

- missing keys in Spanish and Turkish
- English entries in Spanish and Turkish

Fix this consistency by

- [x] Add translations by Google Translate for missing Spanish entries (the whole Spanish i18n will be later proofread)
- [x] Add translations for missing Turkish keys
- [x] Replace English entries in Spanish and Turkish in the correct language

**Comment by behlulbozal** [comment]
[61](https://github.com/Aktion-Sodis/software-main/pull/74)
