### ISSUE TITLE
[Admin-App] Make the app 100% covered by i18n

### ISSUE THREAD

**Issue by apolat2000** [Aktion-Sodis/software-main#62]
There are still some hard coded English text in the app. Search for them, create i18n entries for them and localize them.

IMPORTANT: This task should be started with as late as possible, so that we don't have to go over this again and again.

**Comment by behlulbozal** [comment]
All controls were made on 14.03.2022 ([61](https://github.com/Aktion-Sodis/software-main/pull/74))
