### ISSUE TITLE
[The App] Create storage repository and utility class for image synchronization

### ISSUE THREAD

**Issue by ChristophNetsch** [Aktion-Sodis/software-main#66]
Images need to be synchronized between Flutter frontend and AWS Amplify backend

Implement following classes:
- [ ] storage_repository.dart --> API calls to AWS amplify DataStorage
- [ ] image_synch_service.dart --> utility methods for checking local and online availability of images, ...
- [ ] image_synch_cubit.dart --> provides logic for image synchronization for use within app views

**Comment by ChristophNetsch** [comment]
@CoachBenedetto ergänze gerne, wenn du hierzu noch Gedanken hast.

**Comment by CoachBenedetto** [comment]
Die Dateipfade in Abhängigkeit zu den Objekten sind in lib/utils/s3PathDefinitions/dataStorePaths.dart definiert. Da gerne erstmal reinschauen ob das so weit klar ist. Das file muss entsprechend in den Flutter lib Ordner kopiert werden, damit es verwendbar ist.

Einmal hier ein Link dazu, wie man remote objects in den lokalen File Storage schreibt

https://stackoverflow.com/questions/69644288/how-to-download-file-from-firebase-to-local-phone-storage-in-flutter

Ich würde keinen Storage Cubit machen. Meine Idee wäre folgende gewesen.

Wir machen ein StorageRepository. In diesem hinterlegen wir für jeden möglichen Bildpfad (siehe Pfaddatei) die folgenden Methoden:
 - Future<File?> get...(Parameters)
 - Future<bool> set...(File, Parameters)

Kannst du ja erstmal für einen der Pfade anlegen und dann schauen wir es an.

Beim getten wird versucht local zu getten -> wenn nicht verfügbar -> online

Beim setten wird lokal gesettet und online versucht -> wenn nicht geht -> später synchronisieren

Diese Methoden würde ich dann allerdings über die individuellen Objektbezogenen Repositories referenzieren, damit wir das sozusagen objektbezogen aufrufen können.

Dementsprechend ist auch kein Storage Cubit nötig, da man das dann entsprechend in Objektbezogene Cubits einarbeitet. Wird sonst glaube ich sehr unhandlich.

Zusätzlich wäre eine Sync Option mit Fortschrittswert (optional, aber cool) wichtig (kann man z.B. über einen Stream machen). Da können wir gerne so nochmal zu sprechen, nachdem du dir den Rest mal angeschaut hast. Diese würde ich bei App-Start und bei Eintritt in eine Internetverbindung callen. 

In der Methode müsste dann zunächst die Datenbank aktualisiert werden bzw. einmal alle Daten gezogen werden. Dann sozusagen für alle Daten ein Abgleich online / offline Bild vorgenommen werden und wenn Änderungen zu synchronisieren sind diese synchronisieren. Dabei ist noch die Frage inwiefern im Storage automatisch der Timestamp des letzten updates hinterlegt ist. Selbes gilt auch offline im File-System. Sonst müssen wir uns da noch was überlegen.
