### ISSUE TITLE
[Back-End] API Schema Creation

### ISSUE THREAD

**Issue by CoachBenedetto** [Aktion-Sodis/software-main#9]

**Comment by apolat2000** [comment]
@CoachBenedetto Hi, I noticed that you accidentally tracked the [`.vscode`](https://github.com/Aktion-Sodis/software-main/tree/main/backend/api/.vscode) folder. If you want to untrack it, [this](https://stackoverflow.com/a/1330097/13622041) Stackoverflow thread might be useful.

**Comment by apolat2000** [comment]
@CoachBenedetto Do you consider this issue as should be closed?
